sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: kGJaYEDrOLU1HXHKSZvVjD5EFkvgEluGULKe+5loDa1u2pGCNNyBevZrZdA9TxwPXIwa6EjgC2DDdaKKWrof2Eeqs+GqVbZmJNs/VDEZWQ0W1+nrx/hMpRZEb2tV+JJCrS1c7BgtLGh1/M4wEfcbgYpdnK8//nzJBQ6F2ICqGjyx0AeCY/jKCf/GssgtiZG4eDHVHGQ6xFrLuWcpYvaP5kkcXVZIpfFdJuamXOCJi8R00TP/4Ki+wKPu7oM1V8zXc/mgsQnd80Cd6PVxhGLCiCKhmn5JqsvlYtJbGkdjBEUyd8IilPSj0w1IF3I/zPKtoZF1Q454WoM81CobUyJ0XeIWTOKu4JzkHArfu8j1wz35rV7ZgNShpCr155RO5PTTHqW1jS4X8VFmtGBY3GGfG1+ZxAKNLP2EwOG5BEwlhCGS3HYUKk5QMpt27OjWWSf9sp/Le+tv95mioH+CRKPMfx+An/xpXngHA3pzkhpNWtfUEMVQFuqGHgsy1xPDaThEAcVjv3byNltNjOZMpIO/vsrUNjMC/YTuje1b6V9adYRsK1iizPvG6fFPkxQpcsusWa90JyIGUUBMYKbUjQb4O8Z8i5qN3sPVqCTSpKtx43mi2Z66SakEJDMN+7D2TctKNIJS4wQGJaIJ+n3CzR0UHPMStYaFNJjGXfasNLyOPQY=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: BvchhZqXsF8CzYMbwrHWq45WmaBNQyjOFjZPO6vhdlBENwZp9hyOCnOLtZedr9OR9Dh8mNUAxCFevAqSbklcivaBOfHEVOLh6Y1BE/aNtGWpHOXKEB4VOytUVCD0vW8ldGh3lF0QVl+KYQLFy99y/e/5lzOjFjpgPzPswJgU8smnJuH2DT/65NT2/m63DL6FMMmjhImdEiEW+0Yabro3W77lotH8yZMX+uORLQ8hnFwhZOnvD6a7dFb/jA2j7/EqveDg3CVUh1A/HwDSMGl2Sj6O16gI3NY/OQgNwDYpku5p1x5h61H2tV0nK2i7YPga/VAbrnuWUvC/A4CFpqnBUAaLuTfN57DEyGvaJZYcHpZghaejETb++oq7dUV6nzIkGdFA0x+63QgPWU86Wt+4kAuAmJdh3qjm80xBZ/4P+ZVd+sQh+zq2aUvrDHplYVLH7Huo6QutdEnPGTE5uQxjim8aqgGrs+6F6Bmgp6A61iZ2UvQrX0bMW+fbs31ZWaggTyJvDwo7Y0Eqv7OQ3BLQAwWDfy36qkz43ca3o1OhBVkyMPIjWhc/c3t5OEzJk8ypiUQv04tAAMt8lgje9cWHVI36spnSCTZx34jPUjSxXB8xIVbS0BD4wsdBM0WtvPmKnyDZG2OFZ3RYgtanUIjHntamnp7ZK3kVquZAuMZfOP8=
